const paisesIngles = [
    "Afghanistan",
    "Albania",
    "Germany",
    "Andorra",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Belgium",
    "Bolivia",
    "Brazil",
    "Cameroon",
    "Canada",
    "Chile",
    "China",
    "Cyprus",
    "Colombia",
    "Costa Rica",
    "Croatia",
    "Cuba",
    "Denmark",
    "Dominica",
    "Ecuador",
    "El Salvador",
    "Spain",
    "United States",
    "Philippines",
    "France",
    "Grenada",
    "Greece",
    "Equatorial Guinea",
    "Honduras",
    "India",
    "Ireland",
    "Italy",
    "Japan",
    "Jordan",
    "Lebanon",
    "Maldives",
    "Morocco",
    "Mauritius",
    "Mauritania",
    "Mexico",
    "Norway",
    "Netherlands",
    "Panama",
    "Paraguay",
    "Peru",
    "Poland",
    "Portugal",
    "United Kingdom",
    "Dominican Republic",
    "San Marino",
    "Sweden",
    "Uruguay",
    "Venezuela"
]

const listaPaisesIngles = () => {
    return paisesIngles;
}

export default listaPaisesIngles