const paises = ["Afganistán",
    "Albania",
    "Alemania",
    "Andorra",
    "Argentina",
    "Armenia",
    "Australia",
    "Austria",
    "Bélgica",
    "Bolivia",
    "Brasil",
    "Camerún",
    "Canadá",
    "Chile",
    "China",
    "Chipre",
    "Colombia",
    "Costa Rica",
    "Croacia",
    "Cuba",
    "Dinamarca",
    "Dominica",
    "Ecuador",
    "El Salvador",
    "España",
    "Estados Unidos",
    "Filipinas",
    "Francia",
    "Granada",
    "Grecia",
    "Guinea Ecuatorial",
    "Honduras",
    "India",
    "Irlanda",
    "Italia",
    "Japón",
    "Jordania",
    "Líbano",
    "Maldivas",
    "Marruecos",
    "Mauricio",
    "Mauritania",
    "México",
    "Noruega",
    "Países Bajos",
    "Panamá",
    "Papúa Nueva Guinea",
    "Paraguay",
    "Perú",
    "Polonia",
    "Portugal",
    "Reino Unido",
    "República Dominicana",
    "San Cristóbal y Nieves",
    "San Marino",
    "Santa Lucía",
    "Suecia",
    "Uruguay",
    "Venezuela"]

const listaPaises = () => {
    return paises;
}

export default listaPaises