let paises:Map<string, string> = new Map<string,string>();

const listaPaises = () => {
    paises.set("Afganistán", "AFG")
    paises.set("Albania", "ALB")
    paises.set("Alemania", "DEU")
    paises.set("Andorra", "AND")
    paises.set("Argentina", "ARG")
    paises.set("Armenia", "ARM")
    paises.set("Australia", "AUS")
    paises.set("Austria", "AUT")
    paises.set("Bélgica", "BEL")
    paises.set("Bolivia", "BOL")
    paises.set("Brasil", "BRA")
    paises.set("Camerún", "CMR")
    paises.set("Canadá", "CAN")
    paises.set("Chile", "CHL")
    paises.set("China", "CHN")
    paises.set("Chipre", "CYP")
    paises.set("Colombia", "COL")
    paises.set("Costa Rica", "CRI")
    paises.set("Croacia", "HRV")
    paises.set("Cuba", "CUB")
    paises.set("Dinamarca", "DNK")
    paises.set("Dominica", "DMA")
    paises.set("Ecuador", "ECU")
    paises.set("El Salvador", "SLV")
    paises.set("España", "ESP")
    paises.set("Estados Unidos", "USA")
    paises.set("Filipinas", "PHL")
    paises.set("Francia", "FRA")
    paises.set("Granada", "GRD")
    paises.set("Grecia", "GRC")
    paises.set("Guinea Ecuatorial", "GNQ")
    paises.set("Honduras", "HND")
    paises.set("India", "IND")
    paises.set("Irlanda", "IRL")
    paises.set("Italia", "ITA")
    paises.set("Japón", "JPN")
    paises.set("Jordania", "JOR")
    paises.set("Líbano", "LBN")
    paises.set("Maldivas", "MDV")
    paises.set("Marruecos", "MAR")
    paises.set("Mauricio", "MRT")
    paises.set("Mauritania", "MRT")
    paises.set("México", "MEX")
    paises.set("Noruega", "NOR")
    paises.set("Países Bajos", "NLD")
    paises.set("Panamá", "PAN")
    paises.set("Paraguay", "PRY")
    paises.set("Perú", "PER")
    paises.set("Polonia", "POL")
    paises.set("Portugal", "PRT")
    paises.set("Reino Unido", "GBR")
    paises.set("República Dominicana", "DOM")
    paises.set("San Marino", "SMR")
    paises.set("Suecia", "SWE")
    paises.set("Uruguay", "URY")
    paises.set("Venezuela", "VEN")
    return paises;
}

export default listaPaises